/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AppUser {
  'id' : string,
  'status' : string,
  'passcode' : string,
  'name' : string,
  'createdAt' : Time,
  'role' : string,
  'templeId' : string,
}
export interface AuditLog {
  'id' : string,
  'actorName' : string,
  'actorRole' : string,
  'logTimestamp' : Time,
  'logType' : string,
  'templeId' : string,
  'receiptId' : string,
  'newData' : [] | [string],
  'oldData' : [] | [string],
  'reason' : string,
}
export interface CreateDonationInput {
  'volunteerName' : string,
  'formattedId' : string,
  'date' : string,
  'donorName' : string,
  'time' : string,
  'templeType' : string,
  'event' : string,
  'address' : string,
  'templeId' : string,
  'amount' : bigint,
}
export interface CreateUserInput {
  'id' : string,
  'passcode' : string,
  'name' : string,
  'role' : string,
  'templeId' : string,
}
export interface Donation {
  'volunteerName' : string,
  'formattedId' : string,
  'date' : string,
  'donorName' : string,
  'time' : string,
  'templeType' : string,
  'event' : string,
  'address' : string,
  'timestamp' : Time,
  'templeId' : string,
  'amount' : bigint,
  'recNo' : bigint,
}
export interface Temple {
  'id' : string,
  'name' : string,
  'appeal1' : string,
  'appeal2' : string,
  'appeal3' : string,
  'updatedAt' : Time,
  'address' : string,
  'rules' : string,
}
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'role' : [] | [string],
  'appUserId' : [] | [string],
  'templeId' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addTemple' : ActorMethod<[Temple], undefined>,
  'addTempleWithPin' : ActorMethod<[Temple, string], undefined>,
  'addUser' : ActorMethod<[CreateUserInput], undefined>,
  'addUserWithPin' : ActorMethod<[CreateUserInput, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createDonation' : ActorMethod<[CreateDonationInput], Donation>,
  'createDonationForTemple' : ActorMethod<
    [CreateDonationInput, string],
    Donation
  >,
  'deactivateUser' : ActorMethod<[string], undefined>,
  'deleteDonation' : ActorMethod<[string, string], undefined>,
  'deleteTemple' : ActorMethod<[string], undefined>,
  'deleteTempleWithPin' : ActorMethod<[string, string], undefined>,
  'getAllTemples' : ActorMethod<[], Array<Temple>>,
  'getAuditLogsByReceipt' : ActorMethod<[string], Array<AuditLog>>,
  'getAuditLogsByTemple' : ActorMethod<[string], Array<AuditLog>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCurrentReceiptNumber' : ActorMethod<[string], bigint>,
  'getDonation' : ActorMethod<[string], Donation>,
  'getDonationsByTemple' : ActorMethod<[string], Array<Donation>>,
  'getTemple' : ActorMethod<[string], Temple>,
  'getUser' : ActorMethod<[string], AppUser>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserWithPin' : ActorMethod<[string, string], AppUser>,
  'getUsersByTemple' : ActorMethod<[string], Array<AppUser>>,
  'getUsersByTempleWithPin' : ActorMethod<[string, string], Array<AppUser>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'toggleUserStatus' : ActorMethod<[string], undefined>,
  'toggleUserStatusWithPin' : ActorMethod<[string, string], undefined>,
  'updateDonation' : ActorMethod<[string, Donation, string], undefined>,
  'updateTemple' : ActorMethod<[Temple], undefined>,
  'updateTempleWithPin' : ActorMethod<[Temple, string], undefined>,
  'updateUser' : ActorMethod<[string, CreateUserInput], undefined>,
  'updateUserWithPin' : ActorMethod<
    [string, CreateUserInput, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];