/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Temple = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'appeal1' : IDL.Text,
  'appeal2' : IDL.Text,
  'appeal3' : IDL.Text,
  'updatedAt' : Time,
  'address' : IDL.Text,
  'rules' : IDL.Text,
});
export const CreateUserInput = IDL.Record({
  'id' : IDL.Text,
  'passcode' : IDL.Text,
  'name' : IDL.Text,
  'role' : IDL.Text,
  'templeId' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CreateDonationInput = IDL.Record({
  'volunteerName' : IDL.Text,
  'formattedId' : IDL.Text,
  'date' : IDL.Text,
  'donorName' : IDL.Text,
  'time' : IDL.Text,
  'templeType' : IDL.Text,
  'event' : IDL.Text,
  'address' : IDL.Text,
  'templeId' : IDL.Text,
  'amount' : IDL.Nat,
  'recNo' : IDL.Nat,
});
export const Donation = IDL.Record({
  'volunteerName' : IDL.Text,
  'formattedId' : IDL.Text,
  'date' : IDL.Text,
  'donorName' : IDL.Text,
  'time' : IDL.Text,
  'templeType' : IDL.Text,
  'event' : IDL.Text,
  'address' : IDL.Text,
  'timestamp' : Time,
  'templeId' : IDL.Text,
  'amount' : IDL.Nat,
  'recNo' : IDL.Nat,
});
export const AuditLog = IDL.Record({
  'id' : IDL.Text,
  'actorName' : IDL.Text,
  'actorRole' : IDL.Text,
  'logTimestamp' : Time,
  'logType' : IDL.Text,
  'templeId' : IDL.Text,
  'receiptId' : IDL.Text,
  'newData' : IDL.Opt(IDL.Text),
  'oldData' : IDL.Opt(IDL.Text),
  'reason' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'role' : IDL.Opt(IDL.Text),
  'appUserId' : IDL.Opt(IDL.Text),
  'templeId' : IDL.Opt(IDL.Text),
});
export const AppUser = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'passcode' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Time,
  'role' : IDL.Text,
  'templeId' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addTemple' : IDL.Func([Temple], [], []),
  'addUser' : IDL.Func([CreateUserInput], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createDonation' : IDL.Func([CreateDonationInput], [Donation], []),
  'deactivateUser' : IDL.Func([IDL.Text], [], []),
  'deleteDonation' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'deleteTemple' : IDL.Func([IDL.Text], [], []),
  'getAllTemples' : IDL.Func([], [IDL.Vec(Temple)], ['query']),
  'getAuditLogsByReceipt' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(AuditLog)],
      ['query'],
    ),
  'getAuditLogsByTemple' : IDL.Func([IDL.Text], [IDL.Vec(AuditLog)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCurrentReceiptNumber' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'getDonation' : IDL.Func([IDL.Text], [Donation], ['query']),
  'getDonationsByTemple' : IDL.Func([IDL.Text], [IDL.Vec(Donation)], ['query']),
  'getTemple' : IDL.Func([IDL.Text], [Temple], ['query']),
  'getUser' : IDL.Func([IDL.Text], [AppUser], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUsersByTemple' : IDL.Func([IDL.Text], [IDL.Vec(AppUser)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'toggleUserStatus' : IDL.Func([IDL.Text], [], []),
  'updateDonation' : IDL.Func([IDL.Text, Donation, IDL.Text], [], []),
  'updateTemple' : IDL.Func([Temple], [], []),
  'updateUser' : IDL.Func([IDL.Text, CreateUserInput], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Temple = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'appeal1' : IDL.Text,
    'appeal2' : IDL.Text,
    'appeal3' : IDL.Text,
    'updatedAt' : Time,
    'address' : IDL.Text,
    'rules' : IDL.Text,
  });
  const CreateUserInput = IDL.Record({
    'id' : IDL.Text,
    'passcode' : IDL.Text,
    'name' : IDL.Text,
    'role' : IDL.Text,
    'templeId' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CreateDonationInput = IDL.Record({
    'volunteerName' : IDL.Text,
    'formattedId' : IDL.Text,
    'date' : IDL.Text,
    'donorName' : IDL.Text,
    'time' : IDL.Text,
    'templeType' : IDL.Text,
    'event' : IDL.Text,
    'address' : IDL.Text,
    'templeId' : IDL.Text,
    'amount' : IDL.Nat,
    'recNo' : IDL.Nat,
  });
  const Donation = IDL.Record({
    'volunteerName' : IDL.Text,
    'formattedId' : IDL.Text,
    'date' : IDL.Text,
    'donorName' : IDL.Text,
    'time' : IDL.Text,
    'templeType' : IDL.Text,
    'event' : IDL.Text,
    'address' : IDL.Text,
    'timestamp' : Time,
    'templeId' : IDL.Text,
    'amount' : IDL.Nat,
    'recNo' : IDL.Nat,
  });
  const AuditLog = IDL.Record({
    'id' : IDL.Text,
    'actorName' : IDL.Text,
    'actorRole' : IDL.Text,
    'logTimestamp' : Time,
    'logType' : IDL.Text,
    'templeId' : IDL.Text,
    'receiptId' : IDL.Text,
    'newData' : IDL.Opt(IDL.Text),
    'oldData' : IDL.Opt(IDL.Text),
    'reason' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'role' : IDL.Opt(IDL.Text),
    'appUserId' : IDL.Opt(IDL.Text),
    'templeId' : IDL.Opt(IDL.Text),
  });
  const AppUser = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'passcode' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Time,
    'role' : IDL.Text,
    'templeId' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addTemple' : IDL.Func([Temple], [], []),
    'addUser' : IDL.Func([CreateUserInput], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createDonation' : IDL.Func([CreateDonationInput], [Donation], []),
    'deactivateUser' : IDL.Func([IDL.Text], [], []),
    'deleteDonation' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'deleteTemple' : IDL.Func([IDL.Text], [], []),
    'getAllTemples' : IDL.Func([], [IDL.Vec(Temple)], ['query']),
    'getAuditLogsByReceipt' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(AuditLog)],
        ['query'],
      ),
    'getAuditLogsByTemple' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(AuditLog)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCurrentReceiptNumber' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'getDonation' : IDL.Func([IDL.Text], [Donation], ['query']),
    'getDonationsByTemple' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Donation)],
        ['query'],
      ),
    'getTemple' : IDL.Func([IDL.Text], [Temple], ['query']),
    'getUser' : IDL.Func([IDL.Text], [AppUser], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUsersByTemple' : IDL.Func([IDL.Text], [IDL.Vec(AppUser)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'toggleUserStatus' : IDL.Func([IDL.Text], [], []),
    'updateDonation' : IDL.Func([IDL.Text, Donation, IDL.Text], [], []),
    'updateTemple' : IDL.Func([Temple], [], []),
    'updateUser' : IDL.Func([IDL.Text, CreateUserInput], [], []),
  });
};

export const init = ({ IDL }) => { return []; };