/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Donation {
    volunteerName: string;
    formattedId: string;
    date: string;
    donorName: string;
    time: string;
    templeType: string;
    event: string;
    address: string;
    timestamp: Time;
    templeId: string;
    amount: bigint;
    recNo: bigint;
}
export type Time = bigint;
export interface Temple {
    id: string;
    name: string;
    appeal1: string;
    appeal2: string;
    appeal3: string;
    updatedAt: Time;
    address: string;
    rules: string;
}
export interface AuditLog {
    id: string;
    actorName: string;
    actorRole: string;
    logTimestamp: Time;
    logType: string;
    templeId: string;
    receiptId: string;
    newData?: string;
    oldData?: string;
    reason: string;
}
export interface CreateUserInput {
    id: string;
    passcode: string;
    name: string;
    role: string;
    templeId: string;
}
export interface CreateDonationInput {
    volunteerName: string;
    formattedId: string;
    date: string;
    donorName: string;
    time: string;
    templeType: string;
    event: string;
    address: string;
    templeId: string;
    amount: bigint;
}
export interface UserProfile {
    name: string;
    role?: string;
    appUserId?: string;
    templeId?: string;
}
export interface AppUser {
    id: string;
    status: string;
    passcode: string;
    name: string;
    createdAt: Time;
    role: string;
    templeId: string;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addTemple(temple: Temple): Promise<void>;
    addTempleWithPin(temple: Temple, pin: string): Promise<void>;
    addUser(input: CreateUserInput): Promise<void>;
    addUserWithPin(input: CreateUserInput, pin: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createDonation(input: CreateDonationInput): Promise<Donation>;
    createDonationForTemple(input: CreateDonationInput, pin: string): Promise<Donation>;
    deactivateUser(id: string): Promise<void>;
    deleteDonation(formattedId: string, reason: string): Promise<void>;
    deleteTemple(id: string): Promise<void>;
    deleteTempleWithPin(id: string, pin: string): Promise<void>;
    getAllTemples(): Promise<Array<Temple>>;
    getAuditLogsByReceipt(receiptId: string): Promise<Array<AuditLog>>;
    getAuditLogsByTemple(templeId: string): Promise<Array<AuditLog>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCurrentReceiptNumber(templeId: string): Promise<bigint>;
    getDonation(formattedId: string): Promise<Donation>;
    getDonationsByTemple(templeId: string): Promise<Array<Donation>>;
    getTemple(id: string): Promise<Temple>;
    getUser(id: string): Promise<AppUser>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getUserWithPin(id: string, pin: string): Promise<AppUser>;
    getUsersByTemple(templeId: string): Promise<Array<AppUser>>;
    getUsersByTempleWithPin(templeId: string, pin: string): Promise<Array<AppUser>>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    toggleUserStatus(id: string): Promise<void>;
    toggleUserStatusWithPin(id: string, pin: string): Promise<void>;
    updateDonation(formattedId: string, donation: Donation, reason: string): Promise<void>;
    updateTemple(temple: Temple): Promise<void>;
    updateTempleWithPin(temple: Temple, pin: string): Promise<void>;
    updateUser(id: string, input: CreateUserInput): Promise<void>;
    updateUserWithPin(id: string, input: CreateUserInput, pin: string): Promise<void>;
}
import type { AuditLog as _AuditLog, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addTemple(arg0: Temple): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addTemple(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTemple(arg0);
            return result;
        }
    }
    async addTempleWithPin(arg0: Temple, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addTempleWithPin(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTempleWithPin(arg0, arg1);
            return result;
        }
    }
    async addUser(arg0: CreateUserInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addUser(arg0);
            return result;
        }
    }
    async addUserWithPin(arg0: CreateUserInput, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addUserWithPin(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addUserWithPin(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createDonation(arg0: CreateDonationInput): Promise<Donation> {
        if (this.processError) {
            try {
                const result = await this.actor.createDonation(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createDonation(arg0);
            return result;
        }
    }
    async createDonationForTemple(arg0: CreateDonationInput, arg1: string): Promise<Donation> {
        if (this.processError) {
            try {
                const result = await this.actor.createDonationForTemple(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createDonationForTemple(arg0, arg1);
            return result;
        }
    }
    async deactivateUser(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deactivateUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deactivateUser(arg0);
            return result;
        }
    }
    async deleteDonation(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteDonation(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteDonation(arg0, arg1);
            return result;
        }
    }
    async deleteTemple(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTemple(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTemple(arg0);
            return result;
        }
    }
    async deleteTempleWithPin(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTempleWithPin(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTempleWithPin(arg0, arg1);
            return result;
        }
    }
    async getAllTemples(): Promise<Array<Temple>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTemples();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTemples();
            return result;
        }
    }
    async getAuditLogsByReceipt(arg0: string): Promise<Array<AuditLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAuditLogsByReceipt(arg0);
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAuditLogsByReceipt(arg0);
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAuditLogsByTemple(arg0: string): Promise<Array<AuditLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAuditLogsByTemple(arg0);
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAuditLogsByTemple(arg0);
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCurrentReceiptNumber(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getCurrentReceiptNumber(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCurrentReceiptNumber(arg0);
            return result;
        }
    }
    async getDonation(arg0: string): Promise<Donation> {
        if (this.processError) {
            try {
                const result = await this.actor.getDonation(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDonation(arg0);
            return result;
        }
    }
    async getDonationsByTemple(arg0: string): Promise<Array<Donation>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDonationsByTemple(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDonationsByTemple(arg0);
            return result;
        }
    }
    async getTemple(arg0: string): Promise<Temple> {
        if (this.processError) {
            try {
                const result = await this.actor.getTemple(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTemple(arg0);
            return result;
        }
    }
    async getUser(arg0: string): Promise<AppUser> {
        if (this.processError) {
            try {
                const result = await this.actor.getUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUser(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserWithPin(arg0: string, arg1: string): Promise<AppUser> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserWithPin(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserWithPin(arg0, arg1);
            return result;
        }
    }
    async getUsersByTemple(arg0: string): Promise<Array<AppUser>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUsersByTemple(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUsersByTemple(arg0);
            return result;
        }
    }
    async getUsersByTempleWithPin(arg0: string, arg1: string): Promise<Array<AppUser>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUsersByTempleWithPin(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUsersByTempleWithPin(arg0, arg1);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n12(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n12(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async toggleUserStatus(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleUserStatus(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleUserStatus(arg0);
            return result;
        }
    }
    async toggleUserStatusWithPin(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleUserStatusWithPin(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleUserStatusWithPin(arg0, arg1);
            return result;
        }
    }
    async updateDonation(arg0: string, arg1: Donation, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDonation(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDonation(arg0, arg1, arg2);
            return result;
        }
    }
    async updateTemple(arg0: Temple): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTemple(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTemple(arg0);
            return result;
        }
    }
    async updateTempleWithPin(arg0: Temple, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTempleWithPin(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTempleWithPin(arg0, arg1);
            return result;
        }
    }
    async updateUser(arg0: string, arg1: CreateUserInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUser(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUser(arg0, arg1);
            return result;
        }
    }
    async updateUserWithPin(arg0: string, arg1: CreateUserInput, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUserWithPin(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUserWithPin(arg0, arg1, arg2);
            return result;
        }
    }
}
function from_candid_AuditLog_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AuditLog): AuditLog {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n8(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    actorName: string;
    actorRole: string;
    logTimestamp: _Time;
    logType: string;
    templeId: string;
    receiptId: string;
    newData: [] | [string];
    oldData: [] | [string];
    reason: string;
}): {
    id: string;
    actorName: string;
    actorRole: string;
    logTimestamp: Time;
    logType: string;
    templeId: string;
    receiptId: string;
    newData?: string;
    oldData?: string;
    reason: string;
} {
    return {
        id: value.id,
        actorName: value.actorName,
        actorRole: value.actorRole,
        logTimestamp: value.logTimestamp,
        logType: value.logType,
        templeId: value.templeId,
        receiptId: value.receiptId,
        newData: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.newData)),
        oldData: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.oldData)),
        reason: value.reason
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    role: [] | [string];
    appUserId: [] | [string];
    templeId: [] | [string];
}): {
    name: string;
    role?: string;
    appUserId?: string;
    templeId?: string;
} {
    return {
        name: value.name,
        role: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.role)),
        appUserId: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.appUserId)),
        templeId: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.templeId))
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AuditLog>): Array<AuditLog> {
    return value.map((x)=>from_candid_AuditLog_n4(_uploadFile, _downloadFile, x));
}
function to_candid_UserProfile_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n13(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    role?: string;
    appUserId?: string;
    templeId?: string;
}): {
    name: string;
    role: [] | [string];
    appUserId: [] | [string];
    templeId: [] | [string];
} {
    return {
        name: value.name,
        role: value.role ? candid_some(value.role) : candid_none(),
        appUserId: value.appUserId ? candid_some(value.appUserId) : candid_none(),
        templeId: value.templeId ? candid_some(value.templeId) : candid_none()
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
